### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by rpire** [Rustamxon7/Microverse-portfolio-project#9]
## Hello @Rustamxon7  !

I can see you did a great job. You completed all the requirements with no errors. Congratulations! 🙌

## Suggestion

Try adding a live demo in your README file. This will help reviewers know better how your code truly behaves while in the browser.

Cheers and Happy coding! 🚀

**Comment by Rustamxon7** [comment]
OK, ### thank you so much for reviewing my project. I will correct the mistakes you have made.🤓
